# Docker Compose file for a Django application with a PostgreSQL database

services:
  # Database service
  db:
    # Specifies the PostgreSQL image to use with the version 16.2
    image: postgres:16.2
    # Automatically restart the container if it stops or crashes
    restart: always
    # Mount a volume to persist database data on the host machine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    # Define environment variables for the PostgreSQL configuration
    environment:
      - POSTGRES_DB=postgres       # The default database name
      - POSTGRES_USER=postgres     # The username for the database
      - POSTGRES_PASSWORD=postgres # The password for the database

  # Web application service
  web:
    # Build the web service from the current directory
    build: .
    # Command to start the Django development server, accessible on all interfaces
    command: ["./wait-for-it.sh", "db:5432", "--",
                "python", "/code/SkillSpark/manage.py", "runserver",
                "0.0.0.0:8000"]
    # Automatically restart the container if it stops or crashes
    restart: always
    # Mount the current directory on the host machine to /code inside the container
    # This allows real-time syncing of code changes
    volumes:
      - .:/code
    # Map port 8000 on the host to port 8000 inside the container
    ports:
      - "8000:8000"
    # Define environment variables for the Django application and database connection
    environment:
      - DJANGO_SETTINGS_MODULE=SkillSpark.settings.prod # Django settings module to use in production
      - POSTGRES_DB=postgres       # Database name, must match the db service
      - POSTGRES_USER=postgres     # Username for connecting to the database
      - POSTGRES_PASSWORD=postgres # Password for connecting to the database
    # Define service dependencies; ensures the database is started before the web service
    depends_on:
      - db
